/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitas.Casilla;
import civitas.CasillaCalle;
import civitas.CasillaSorpresa;

/**
 *
 * @author alejandronietoalarcon
 */
public class CasillaPanel extends javax.swing.JPanel {

    
    private Casilla casillaActual;
    /**
     * Creates new form CasillaPanel
     */
    public CasillaPanel() {
        initComponents();
    }
    
    public void setCasilla(Casilla casilla){
        
        this.mostrarLabels();
        
        this.nombreCasilla.setText(casilla.getNombre());
        
        
        if(casilla instanceof CasillaCalle){
            
            this.casillaActual = (CasillaCalle) casilla;
            
            this.precioCompra.setText(String.valueOf((((CasillaCalle) this.casillaActual).getPrecioCompra())));
            
            this.precioEdificacion.setText(String.valueOf(((CasillaCalle) this.casillaActual).getPrecioEdificar()));
            
            this.numCasas.setText(String.valueOf(((CasillaCalle) this.casillaActual).getNumCasas()));
            
            this.numHoteles.setText(String.valueOf(((CasillaCalle) this.casillaActual).getNumHoteles()));
           
            if(((CasillaCalle) this.casillaActual).tienePropietario()){
                this.checkBoxPropietario.setSelected(true);
            }
            
        } else if (casilla instanceof CasillaSorpresa){
            
            this.casillaActual = (CasillaSorpresa) casilla;
            
            this.ocultarLabels();
            

        } else if (casilla instanceof Casilla){
            
            this.casillaActual = casilla;
            
            this.ocultarLabels();
            
        }
        
    
    }
    
    private void mostrarLabels(){
        this.jLabel2.setVisible(true);
        this.jLabel3.setVisible(true);
        this.jLabel4.setVisible(true);
        this.jLabel5.setVisible(true);
        this.jLabel6.setVisible(true);
        
        this.precioCompra.setVisible(true);
        this.precioEdificacion.setVisible(true);
        this.numCasas.setVisible(true);
        this.numHoteles.setVisible(true);
        this.checkBoxPropietario.setVisible(true);
    }
    
    private void ocultarLabels(){
        this.jLabel2.setVisible(false);
        this.jLabel3.setVisible(false);
        this.jLabel4.setVisible(false);
        this.jLabel5.setVisible(false);
        this.jLabel6.setVisible(false);

        this.precioCompra.setVisible(false);
        this.precioEdificacion.setVisible(false);
        this.numCasas.setVisible(false);
        this.numHoteles.setVisible(false);
        this.checkBoxPropietario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreCasilla = new javax.swing.JTextField();
        precioCompra = new javax.swing.JTextField();
        precioEdificacion = new javax.swing.JTextField();
        numCasas = new javax.swing.JTextField();
        numHoteles = new javax.swing.JTextField();
        checkBoxPropietario = new javax.swing.JCheckBox();

        jLabel1.setText("Nombre");

        jLabel2.setText("Precio de compra");

        jLabel3.setText("Precio de edificación");

        jLabel4.setText("Número de casas");

        jLabel5.setText("Número de hoteles");

        jLabel6.setText("¿Tiene propietario?");

        nombreCasilla.setEditable(false);
        nombreCasilla.setText("jTextField1");

        precioCompra.setEditable(false);
        precioCompra.setText("jTextField2");

        precioEdificacion.setEditable(false);
        precioEdificacion.setText("jTextField3");

        numCasas.setEditable(false);
        numCasas.setText("jTextField4");

        numHoteles.setEditable(false);
        numHoteles.setText("jTextField5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(precioCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(nombreCasilla)
                    .addComponent(precioEdificacion)
                    .addComponent(numCasas)
                    .addComponent(numHoteles)
                    .addComponent(checkBoxPropietario))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(precioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(precioEdificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(checkBoxPropietario))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxPropietario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombreCasilla;
    private javax.swing.JTextField numCasas;
    private javax.swing.JTextField numHoteles;
    private javax.swing.JTextField precioCompra;
    private javax.swing.JTextField precioEdificacion;
    // End of variables declaration//GEN-END:variables
}
