/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import civitas.CivitasJuego;
import civitas.Diario;
import civitas.Jugador;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author alejandronietoalarcon
 */
public class CivitasView extends javax.swing.JFrame implements Vista {

    CivitasJuego juego;
    
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        VistaDado.createInstance(this);

    }
    
    public void setCivitasJuego(CivitasJuego juego){
        this.juego = juego;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        casillaPanel1 = new GUI.CasillaPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        operacionJuego = new javax.swing.JTextField();
        labelRanking = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaRanking = new javax.swing.JTextArea();
        jugadorDatos = new GUI.JugadorPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CIVITAS JUEGO");

        jLabel2.setText("JUGADOR ACTUAL");

        jLabel3.setText("CASILLA ACTUAL");

        jLabel4.setText("Siguiente operacion");

        operacionJuego.setEditable(false);

        labelRanking.setText("RANKING");

        areaRanking.setEditable(false);
        areaRanking.setColumns(20);
        areaRanking.setRows(5);
        jScrollPane1.setViewportView(areaRanking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(149, 149, 149))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jugadorDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(casillaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(268, 268, 268)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(operacionJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 8, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(labelRanking))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(operacionJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casillaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jugadorDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(labelRanking)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    @Override
    public void actualiza() {
        this.labelRanking.setVisible(false);
        this.areaRanking.setVisible(false);
        this.jugadorDatos.setJugador(this.juego.getJugadorActual());
        this.casillaPanel1.setCasilla(this.juego.getTablero().getCasilla(this.juego.getJugadorActual().getCasillaActual()));
        
        if(juego.finalDelJuego()){
            this.areaRanking.setVisible(true);
            this.labelRanking.setVisible(true);
            
            ArrayList<Jugador> jugadoresRanking = this.juego.ranking();
          
            String salida = "";
            int contador = 1;
            for(Jugador jugador : jugadoresRanking){
                salida += "\n" + contador + " - " + jugador.getNombre();
            }
            this.areaRanking.setText(salida);
        }
        
        repaint();
        revalidate();
    }

    @Override
    public void pausa() {
           int val= JOptionPane.showConfirmDialog(null, "¿Continuar?", "Siguiente paso", JOptionPane.YES_NO_OPTION);
           if (val==1) 
               System.exit(0);    
    }

    @Override
    public Respuesta comprar() {
        int opcion = 1-JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
        if(opcion == 1)
            return Respuesta.SI;
        else
            return Respuesta.NO;
    }

    @Override
    public OperacionInmobiliaria elegirOperacion() {
        GestionarDialog gestionD = new GestionarDialog(this);
        int gestionElegida = gestionD.getGestion();
        if(gestionElegida == 0)
            return OperacionInmobiliaria.CONSTRUIR_CASA;
        else if(gestionElegida == 1)
            return OperacionInmobiliaria.CONSTRUIR_HOTEL;
        else 
            return OperacionInmobiliaria.TERMINAR;
       
    }

    @Override
    public int elegirPropiedad() {
        PropiedadDialog propiedadD = new PropiedadDialog(this, this.juego.getJugadorActual());
        return propiedadD.getPropiedadElegida();
    }

    @Override
    public void mostrarSiguienteOperacion(OperacionJuego operacion) {
        this.operacionJuego.setText(String.valueOf(operacion));
        if(operacion == OperacionJuego.AVANZAR){
            VistaDado.createInstance(this);            
        }
        
        this.repaint();
     
    }

    @Override
    public void mostrarEventos() {
        if(!Diario.getInstance().getEventos().isEmpty()){
            DiarioDialog diarioD = new DiarioDialog(this);
        }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaRanking;
    private GUI.CasillaPanel casillaPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.JugadorPanel jugadorDatos;
    private javax.swing.JLabel labelRanking;
    private javax.swing.JTextField operacionJuego;
    // End of variables declaration//GEN-END:variables
}
